### ISSUE TITLE
Main to-do list

### ISSUE THREAD

**Issue by qubistt** [Qubisted/Pythonly-GameJam#3]
- [ ] Create terrain using **Perlin Noise**
- [ ] Fix scene switching using **.commands**
- [ ] Try out the **pause()** function
- [ ] Work on levels up to 10
